name: retail_pipeline
version: '1.0.0'
config-version: 2

profile: 'retail_pipeline'

model-paths: ["models"]
test-paths: ["tests"]

models:
  retail_pipeline:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold