retail_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: bronze
      keyfile: /opt/airflow/gcp-key.json
      threads: 4
      timeout_seconds: 300
      location: US