version: 2

sources:
  - name: bronze
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: bronze
    tables:
      - name: staging_raw_data
        description: "Raw Superstore data loaded from CSV by Python script"